# Generated by Django 4.0 on 2021-12-29 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_alter_user_user_email_alter_user_user_genre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_email',
        ),
    ]
