# Generated by Django 4.0 on 2021-12-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0005_user_user_dob_user_user_guild_rank_user_user_music_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_name', models.CharField(max_length=50)),
                ('guild_image', models.ImageField(upload_to='guild-image')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(null=True, upload_to='user-image'),
        ),
    ]
