# Generated by Django 4.0 on 2021-12-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0006_guild_alter_user_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='guild_image',
            field=models.FileField(upload_to='guild-image'),
        ),
    ]
