# Generated by Django 4.0 on 2021-12-29 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0007_alter_guild_guild_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_guild',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baseapp.guild'),
        ),
    ]
