# Generated by Django 4.0 on 2021-12-29 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0010_remove_guildrank_guild_rank_belongs_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guildrank',
            name='guild_rank_points',
        ),
    ]
