# Generated by Django 4.0 on 2021-12-29 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0011_remove_guildrank_guild_rank_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_guild_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baseapp.guildrank'),
        ),
        migrations.CreateModel(
            name='GuildLeaderBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baseapp.guild')),
                ('guild_rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baseapp.guildrank')),
                ('guild_rank_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baseapp.user')),
            ],
        ),
    ]
