# Generated by Django 4.0 on 2021-12-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0012_alter_user_user_guild_rank_guildleaderboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('rank_min_point', models.IntegerField(blank=True, null=True)),
                ('rank_max_point', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
