# Generated by Django 4.0 on 2021-12-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0013_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='rank_image',
            field=models.FileField(default=1, upload_to='rank-image'),
            preserve_default=False,
        ),
    ]
