# Generated by Django 4.0 on 2021-12-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0014_rank_rank_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='rank_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rank',
            name='rank_hp_boost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
