# Generated by Django 4.0 on 2021-12-30 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0015_rank_rank_color_rank_rank_hp_boost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rank',
            old_name='rank_max_point',
            new_name='rank_max_xp',
        ),
        migrations.RenameField(
            model_name='rank',
            old_name='rank_min_point',
            new_name='rank_min_xp',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baseapp.rank'),
        ),
    ]
