# Generated by Django 4.0 on 2021-12-30 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0017_rename_rank_max_xp_rank_rank_max_points_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rank',
            old_name='rank_max_points',
            new_name='rank_max_point',
        ),
        migrations.RenameField(
            model_name='rank',
            old_name='rank_min_points',
            new_name='rank_min_point',
        ),
    ]
