# Generated by Django 4.0 on 2021-12-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0019_guildrank_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guildrank',
            name='slug',
        ),
        migrations.AddField(
            model_name='guild',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
