# Generated by Django 4.0 on 2021-12-31 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0020_remove_guildrank_slug_guild_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='guildrank',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
