# Generated by Django 4.0 on 2022-01-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0023_genre_alter_user_user_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_xp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
