# Generated by Django 4.0 on 2022-01-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0024_alter_user_user_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_max_hp',
            field=models.IntegerField(default=100, null=True),
        ),
    ]
