# Generated by Django 4.0 on 2022-01-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0030_remove_user_user_buy_ins_remove_user_user_tickets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userticket',
            name='num_of_tickets',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
