# Generated by Django 4.0 on 2022-01-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0031_alter_userticket_num_of_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_gold',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
